time_source_destroy(ts_game_starting);
time_source_destroy(ts_rolling_dice);
time_source_destroy(ts_card_display);
time_source_destroy(ts_jail_animation);
time_source_destroy(ts_game_ending);
time_source_destroy(ts_return_to_lobby);